CREATE TABLE USUARIOS (
      ID NUMBER  PRIMARY KEY,
      NUMERODNI VARCHAR2(100),
      NOMBRES VARCHAR2(250),
      APELLIDOS VARCHAR2(250),
      EMAIL VARCHAR2(100),
      TELEFONO VARCHAR2(100),
      ESTADO CHAR(1),
      TIPOUSUARIO VARCHAR2(2)
);

CREATE SEQUENCE USUARIOS_SEQ
 START WITH     1
 INCREMENT BY   1;  

--TIPO USUARIO : 01-ALUMNO / 02-DOCENTE
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.nextVal, '12345678', 'Wendy', 'Flores Cardenas', 'wendy.flores@gmail.com', '997821460', 1, '01');
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.nextVal, '12345671', 'Carla', 'Lopez Arias', 'carla@gmail.com', '997821461', 1, '01');
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.nextVal, '12345672', 'Luis', 'Flores Arias', 'luis@gmail.com', '997821462', 1,'02');
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.nextVal, '12345673', 'Miguel', 'Carrillo Carrillo', 'miguel@gmail.com', '997821430', 1, '02');

CREATE TABLE LIBROS (
      ID NUMBER PRIMARY KEY,
      NOMBRE VARCHAR(250),
      CATEGORIA VARCHAR(250),
      AUTOR VARCHAR(250),
      PAIS VARCHAR(250),
      FECHAPUBLICACION DATE,
      EDITORIAL  VARCHAR(250)
	  ); 
      

CREATE SEQUENCE LIBROS_SEQ
 START WITH     1
 INCREMENT BY   1;  


INSERT INTO LIBROS VALUES (LIBROS_SEQ.nextVal, 'Manual Practica Redes', 'Informática', 'Julio S.', 'Perú', TO_DATE('2022-03-21', 'YYYY-MM-DD'),'EDITORI SA.');
INSERT INTO LIBROS VALUES (LIBROS_SEQ.nextVal, 'Manual Practica Python', 'Informática', 'Luis Sanchez S.', 'Perú', TO_DATE('2019-03-21', 'YYYY-MM-DD'),'EDITORI SA.');
INSERT INTO LIBROS VALUES (LIBROS_SEQ.nextVal, 'Marketing', 'Ciencias de la comunicación', 'Julio S.', 'Perú', TO_DATE('2021-03-21', 'YYYY-MM-DD'),'EDITORI SA.');
INSERT INTO LIBROS VALUES (LIBROS_SEQ.nextVal, 'Economía y Finanzas', 'Economía', 'Marti Sir S.', 'Perú', TO_DATE('2022-03-21', 'YYYY-MM-DD'),'EDITORI SA.');
INSERT INTO LIBROS VALUES (LIBROS_SEQ.nextVal, 'Administración', 'Economía', 'Julio S.', 'Perú', TO_DATE('2022-03-21', 'YYYY-MM-DD'),'VISOR SA.');
INSERT INTO LIBROS VALUES (LIBROS_SEQ.nextVal, 'Manual Practica c++', 'Informática', 'Marti Sir S.', 'Perú', TO_DATE('2020-03-21', 'YYYY-MM-DD'),'VISOR SA.');

CREATE TABLE PRESTAMOLIBROS (
      ID NUMBER PRIMARY KEY,
      IDLIBROS NUMBER,
      IDUSUARIOS NUMBER,
      TIPOLECTURA VARCHAR(250),
      FECHAPRESTAMO DATE,
      FECHADEVOLUCION DATE,
      CONSTRAINT fk_libros_id
        FOREIGN KEY (IDLIBROS)
        REFERENCES LIBROS(ID),
      CONSTRAINT fk_usuarios_id
        FOREIGN KEY (IDUSUARIOS)
        REFERENCES USUARIOS(ID)
	  ); 

CREATE SEQUENCE PRESTAMOLIBROS_SEQ
 START WITH     1
 INCREMENT BY   1;  

ALTER TABLE PRESTAMOLIBROS MODIFY ID DEFAULT PRESTAMOLIBROS_SEQ.NEXTVAL;
      