// <auto-generated />
namespace SOL_WENDY_FLORES.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class MigrationInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigrationInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202303220042151_MigrationInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
